site_name: RustyNum Docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    - search.highlight
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
  palette:
    - scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

site_url: https://rustynum.com
repo_url: https://github.com/IgorSusmelj/rustynum
repo_name: RustyNum
docs_dir: docs

nav:
  - Home:
      - index.md
      - Installation: installation.md
      - Quick Start: quick-start.md
      - Tutorials:
          - tutorials/index.md
          - Getting Better Matrix Operations with RustyNum: tutorials/better-matrix-operations.md
          - Replacing Core NumPy Calls for Faster Analytics: tutorials/replacing-numpy-for-faster-analytics.md
          - Streamlining Machine Learning Preprocessing: tutorials/streamlining-machine-learning-preprocessing.md
      - API Reference: api/index.md
plugins:
  - search
  - blog
  - git-revision-date-localized:
      type: date
  - mkdocstrings:
      handlers:
        python:
          options:
            show_signature: true
            show_source: false

extra:
  analytics:
    provider: google
    property: G-85020MLN2G
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_javascript:
  - assets/js/analytics.js

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
