name: Build and Upload Wheels to PyPI

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: py${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [38, 39, 310, 311, 312]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
        working-directory: bindings/python

      - name: Build Wheels
        run: |
          python setup.py bdist_wheel
        working-directory: bindings/python

      - uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: bindings/python/dist/*.whl

  build_wheels_aarch64:
    name: py${{ matrix.python-version }} on ${{ matrix.os }} (aarch64)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [38, 39, 310, 311, 312]
    steps:
      - uses: actions/checkout@v4

      - name: Setup up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
        working-directory: bindings/python

      - name: Build Wheels (ARM64)
        run: |
          python setup.py bdist_wheel
        working-directory: bindings/python

      - uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: bindings/python/dist/*.whl

  build_sdist:
    name: sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.9"
      - name: Build sdist
        run: |
          pip install --upgrade build
          python -m build --sdist
        working-directory: bindings/python
      - uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: bindings/python/dist/*.tar.gz

  upload_to_pypi:
    name: Upload to PyPI
    needs: [build_wheels, build_wheels_aarch64, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install twine
        run: pip install twine
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Upload Distribution to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
